// <auto-generated />
namespace ClinicManager.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_doctors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_doctors));
        
        string IMigrationMetadata.Id
        {
            get { return "201809231228062_add_doctors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
